# Generated by Django 4.2.7 on 2024-02-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_photo_car_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, default='C:\\Users\\bruno\\Pictures\\padrao.jpg', null=True, upload_to='cars/'),
        ),
    ]
