# Generated by Django 4.2.7 on 2024-02-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, default='cars/padrao.jpg', null=True, upload_to='cars/'),
        ),
    ]
